### ISSUE TITLE
Nesting selectors

### ISSUE THREAD

**Issue by luchian** [pixeltrove/ignition-vanilla#112]
Placing selectors within other selectors is a useful Sass feature. Employing this technique to define descendants and variants is likely to lead to code that is more succinct and less error-prone.

**Comment by luchian** [comment]
For example, `blockquote` styles
```css
blockquote {
  margin: 0 0 $space-large-4;
  font-size: $font-size-large-4;
  line-height: $line-height-small-1;
}

blockquote p {
  margin-bottom: $space-small-3;
}
```
can be refactored as
```css
blockquote {
  margin: 0 0 $space-large-4;
  font-size: $font-size-large-4;
  line-height: $line-height-small-1;

  p {
    margin-bottom: $space-small-3;
  }
}
```
