### ISSUE TITLE
Order items and properties

### ISSUE THREAD

**Issue by luchian** [pixeltrove/ignition-vanilla#40]
Main files such as `ignition.scss` should list items alphabetically to increase findability. Selectors and declarations may not benefit from this type of arrangement as logical grouping makes them easier to review and understand.

**Comment by luchian** [comment]
Properties should be grouped in accordance with a single principle. Positioning properties should come first, followed by those that establish box sizing and display style, size and spacing, font attributes, text-related traits, color, and finally background, shadows and other decorative styles.

**Comment by luchian** [comment]
`opacity` might work better along the display properties.

**Comment by luchian** [comment]
This is a more complete example of how properties should be ordered.

```scss
.selector {
  // Content
  content: "";
  // Position
  position: absolute;
  z-index: 1;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  // Opacity and visibility
  opacity: 0.33;
  visibility: visible;
  // Display
  display: flex;
  overflow: hidden;
  // Flex
  flex-wrap: wrap;
  // Size
  box-sizing: border-box;
  width: 10rem;
  height: 10rem;
  padding: 1rem;
  border: 1px solid #d6d6d6;
  margin: 1rem;
  // Typography
  font-family: sans-serif;
  font-size: 1rem;
  text-transform: uppercase;
  // Color
  color: #fff;
  // Background, shadow, and outline
  background: #fff;
  box-shadow: 0 0 0 3px #ebebeb;
  outline: none;
  // Other
  cursor: pointer;
  // Animation
  animation: pulse 4s infinite;
  // Appearance
  appearance: none;
  // Fixes
  -webkit-text-size-adjust: 100%;
}
```
